#spcloud:
#  cassandra:
#    password: cassandra
#    username: cassandra
#    port: 9042
#    contact:
#      point: localhost
#    keyspace:
#      name: springcloud

#spcloud:
#  cassandra:
#    keyspace:
#      name: springcloud
#    port: 9042
#    username: cassandra
#    password: cassandra
#    contact:
#      point: 127.0.0.1
#    change-log: classpath:db-changelog/changelog-master.json

spring:
  config:
    liquibase.change-log: classpath:db-changelog/changelog-master.json

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    cassandra:
      port: 9042
      contact-points: 127.0.0.1
      keyspace-name: springcloud
      username: cassandra
      password: cassandra
      local-datacenter: datacenter1


#spring:
#  liquibase:
#    url: jdbc:cassandra://localhost:9042/springcloud;DefaultKeyspace=springcloud
#    driver: com.datastax.oss.driver.api.core.CqlSession
#    classpath: classpath:db-changelog/changelog-master.json
#    changeLogFile: classpath:db-changelog/changelog-master.json
#    cassandra:
#      username: cassandra
#      password: cassandra
#      contact:
#        point: 127.0.0.1
#      port: 9042
#      keyspace:
#        name: springcloud
#    default-schema: springcloud
#    change-log: classpath:db-changelog/changelog-master.json
